name: "build"
on:
  push:
    branches: "**"
    tags-ignore: [ "**" ]
  pull_request:
jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v6"
      - name: "setup jdk"
        uses: "actions/setup-java@v5"
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: "setup gradle"
        uses: gradle/actions/setup-gradle@v5
      - name: "build"
        run: "./gradlew build"
      - name: "extract client dist"
        run: |
          mkdir -p endermux-client-dist
          for archive in endermux-client/build/distributions/*.tar; do
            tar -xf "$archive" -C endermux-client-dist
          done
      - name: "upload artifacts"
        uses: actions/upload-artifact@v6
        with:
          name: 'endermux-client'
          path: 'endermux-client-dist/*'
